name: Generates Update

on:
  pull_request:
    types:
      - closed

jobs:
  upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: JQ
        run: sudo apt-get install jq
        
      - name: YAML to JSON
        run: |
          for file in /Installer/Configs/*.asset; do
            cat "$file" >> configs.asset
          done
          cat configs.asset | jq -s '.' > configs.json
          
