name: Generates Update

on:
  #  pull_request:
  #    types:
  #      - closed
  workflow_dispatch:

jobs:
  build:
    #    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JQ and COREUTILS
        run: |
          sudo apt-get install jq
          sudo apt-get install coreutils

      - name: CONFIGS to JSON
        run: |
          echo "{\"configs\": [" > output.json
          for file in Editor/Installer/Configs/*.asset; do
            name=$(basename "$file")
            content=$(cat "$file" | awk '{gsub(/\\/, "\\\\\\\\"); gsub(/"/, "\\\""); printf "%s\\n", $0}')
            crc=$(cat "$file" | cksum | awk '{print $1}')
            echo "{\"name\": \"$name\", \"content\": \"$content\", \"crc\": \"crc32:$crc\"}," >> output.json
          done
          echo "{}]}" >> output.json
          cat output.json | jq 'del(.[] | select(. == {}))' > configs.json

      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: configs
          path: configs.json
          
