name: Generates Update

on:
#  pull_request:
#    types:
#      - closed
  workflow_dispatch:

jobs:
  build:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: JQ
        run: sudo apt-get install jq
        
      - name: CONFIGS to JSON
        run: |
          echo "[" > output.json
          for file in Editor/Installer/Configs/*.asset; do
            name=$(basename "$file")
            content=$(cat "$file" | awk '{printf "%s\\n", $0}')
            crc=$(crc32 "$file")
            echo "{\"name\": \"$name\", \"content\": \"$content\", \"crc\": \"$crc\"}," >> output.json
          done
          echo "{}]" >> output.json
          cat output.json | jq 'del(.[] | select(. == {}))' > configs.json
          
