name: Generates Update

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: JQ
        run: sudo apt-get install jq
        
      - name: YAML to JSON
        run: |
          for file in Editor/Installer/Configs/*.asset; do
            cat "$file" >> configs-$(basename "$file").asset
          done
          cat configs-*.asset | jq -s '.' > configs.json
          
